name: strict
description: Strict rules set for dart analyzer and linter
version: 1.0.0
author: nyarian <orkay255@gmail.com>
homepage: https://github.com/nyarian/strict

environment:
  sdk: ">=2.0.0 <3.0.0"
